

def get_states():
    return [
    {"code":"AL", "name":"Alabama", "enabled": True},
    {"code":"AK", "name":"Alaska", "enabled": True},
    {"code":"AZ", "name":"Arizona", "enabled": True},
    {"code":"AR", "name":"Arkansas", "enabled": True},
    {"code":"CA", "name":"California", "enabled": True},
    {"code":"CO", "name":"Colorado", "enabled": False},
    {"code":"CT", "name":"Connecticut", "enabled": False},
    {"code":"DE", "name":"Delaware", "enabled": True},
    {"code":"FL", "name":"Florida", "enabled": False},
    {"code":"GA", "name":"Georgia", "enabled": True},
    {"code":"HI", "name":"Hawaii", "enabled": True},
    {"code":"ID", "name":"Idaho", "enabled": True},
    {"code":"IL", "name":"Illinois", "enabled": False},
    {"code":"IN", "name":"Indiana", "enabled": False},
    {"code":"IA", "name":"Iowa", "enabled": True},
    {"code":"KS", "name":"Kansas", "enabled": True},
    {"code":"KY", "name":"Kentucky", "enabled": True},
    {"code":"LA", "name":"Louisiana", "enabled": True},
    {"code":"ME", "name":"Maine", "enabled": False},
    {"code":"MD", "name":"Maryland", "enabled": False},
    {"code":"MA", "name":"Massachusetts", "enabled": False},
    {"code":"MI", "name":"Michigan", "enabled": True},
    {"code":"MN", "name":"Minnesota", "enabled": False},
    {"code":"MS", "name":"Mississippi", "enabled": True},
    {"code":"MO", "name":"Missouri", "enabled": False},
    {"code":"MT", "name":"Montana", "enabled": True},
    {"code":"NE", "name":"Nebraska", "enabled": True},
    {"code":"NV", "name":"Nevada", "enabled": True},
    {"code":"NH", "name":"New Hampshire", "enabled": False},
    {"code":"NJ", "name":"New Jersey", "enabled": False},
    {"code":"NM", "name":"New Mexico", "enabled": True},
    {"code":"NY", "name":"New York", "enabled": False},
    {"code":"NC", "name":"North Carolina", "enabled": False},
    {"code":"ND", "name":"North Dakota", "enabled": False},
    {"code":"OH", "name":"Ohio", "enabled": False},
    {"code":"OK", "name":"Oklahoma", "enabled": True},
    {"code":"OR", "name":"Oregon", "enabled": True},
    {"code":"PA", "name":"Pennsylvania", "enabled": False},
    {"code":"RI", "name":"Rhode Island", "enabled": True},
    {"code":"SC", "name":"South Carolina", "enabled": True},
    {"code":"SD", "name":"South Dakota", "enabled": True},
    {"code":"TN", "name":"Tennessee", "enabled": True},
    {"code":"TX", "name":"Texas", "enabled": True},
    {"code":"UT", "name":"Utah", "enabled": True},
    {"code":"VT", "name":"Vermont", "enabled": True},
    {"code":"VA", "name":"Virginia", "enabled": True},
    {"code":"WA", "name":"Washington", "enabled": True},
    {"code":"WV", "name":"West Virginia", "enabled": True},
    {"code":"WI", "name":"Wisconsin", "enabled": True},
    {"code":"WY", "name":"Wyoming", "enabled": True},
    ]
    