#!/bin/sh -e
export DATABASE_NAME=taa-test
export SQLALCHEMY_ECHO=False
export SERVER_PORT=5050
export PORT=$SERVER_PORT
python run_server.py &
SERVER_ID=$!
behave tests/integration_features/browser
kill $SERVER_ID
