"""add can_override_states to products table

Revision ID: 04f80b421267
Revises: 72600a788388
Create Date: 2016-07-27 19:22:43.985203

"""

# revision identifiers, used by Alembic.
revision = '04f80b421267'
down_revision = '72600a788388'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'ongoing_enrollment_type')
    op.drop_column('cases', 'open_enrollment_type')
    op.add_column('products', sa.Column('can_override_states', sa.Boolean(), server_default='FALSE', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'can_override_states')
    op.add_column('cases', sa.Column('open_enrollment_type', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('ongoing_enrollment_type', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    ### end Alembic commands ###
