"""changing case riders to JSON field

Revision ID: 11f6fc11b5eb
Revises: 39386c5ffac9
Create Date: 2015-12-10 21:24:48.166750

"""

# revision identifiers, used by Alembic.
revision = '11f6fc11b5eb'
down_revision = '39386c5ffac9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_agents_agent_code'), 'agents', ['agent_code'], unique=False)
    op.create_index(op.f('ix_agents_stormpath_url'), 'agents', ['stormpath_url'], unique=False)
    op.drop_index('ix_agents_code', table_name='agents')
    op.drop_index('ix_agents_url', table_name='agents')

    op.create_index(op.f('ix_api_tokens_api_token'), 'api_tokens', ['api_token'], unique=False)
    op.create_index(op.f('ix_api_tokens_stormpath_url'), 'api_tokens', ['stormpath_url'], unique=False)
    op.drop_index('ix_api_tokens_token', table_name='api_tokens')
    op.drop_index('ix_api_tokens_url', table_name='api_tokens')

    op.create_index(op.f('ix_case_census_case_id'), 'case_census', ['case_id'], unique=False)
    op.drop_index('ix_case_census_records_case', table_name='case_census')

    op.create_index(op.f('ix_case_enrollment_periods_case_id'), 'case_enrollment_periods', ['case_id'], unique=False)
    op.drop_index('ix_case_enrollment_periods_case', table_name='case_enrollment_periods')

    op.drop_index('ix_cases_product_product', table_name='case_products')
    op.create_index(op.f('ix_cases_case_token'), 'cases', ['case_token'], unique=False)

    op.drop_index('ix_cases_token', table_name='cases')
    op.create_index(op.f('ix_enrollment_application_coverage_enrollment_application_id'), 'enrollment_application_coverage', ['enrollment_application_id'], unique=False)
    op.drop_index('ix_enrollment_app_coverages_enrollment_id', table_name='enrollment_application_coverage')
    op.create_index(op.f('ix_enrollment_applications_case_id'), 'enrollment_applications', ['case_id'], unique=False)
    op.create_index(op.f('ix_enrollment_applications_census_record_id'), 'enrollment_applications', ['census_record_id'], unique=False)
    op.drop_index('ix_enrollment_applications_case', table_name='enrollment_applications')
    op.drop_index('ix_enrollment_applications_census_record', table_name='enrollment_applications')
    op.create_index(op.f('ix_enrollment_import_batch_items_enrollment_batch_id'), 'enrollment_import_batch_items', ['enrollment_batch_id'], unique=False)
    op.drop_index('ix_enrollment_batch_items_batch', table_name='enrollment_import_batch_items')
    op.create_index(op.f('ix_enrollment_import_batches_case_token'), 'enrollment_import_batches', ['case_token'], unique=False)
    op.create_index(op.f('ix_enrollment_import_batches_log_hash'), 'enrollment_import_batches', ['log_hash'], unique=False)
    op.drop_index('ix_enrollment_batches_case', table_name='enrollment_import_batches')
    op.drop_index('ix_enrollment_batches_hash', table_name='enrollment_import_batches')
    op.create_index(op.f('ix_form_template_tabs_form_template_id'), 'form_template_tabs', ['form_template_id'], unique=False)
    op.drop_index('ix_form_template_tabs_template', table_name='form_template_tabs')
    op.create_index(op.f('ix_products_gi_bypass_questions_product_id'), 'products_gi_bypass_questions', ['product_id'], unique=False)
    op.drop_index('ix_products_gi_bypass_questions_product', table_name='products_gi_bypass_questions')
    op.create_index(op.f('ix_products_gi_criteria_product_id'), 'products_gi_criteria', ['product_id'], unique=False)
    op.drop_index('ix_product_criteria_product', table_name='products_gi_criteria')
    op.create_index(op.f('ix_self_enrollment_email_batches_case_id'), 'self_enrollment_email_batches', ['case_id'], unique=False)
    op.drop_index('ix_self_enroll_email_batches_case', table_name='self_enrollment_email_batches')
    op.create_index(op.f('ix_self_enrollment_email_log_batch_id'), 'self_enrollment_email_log', ['batch_id'], unique=False)
    op.create_index(op.f('ix_self_enrollment_email_log_link_id'), 'self_enrollment_email_log', ['link_id'], unique=False)
    op.drop_index('ix_email_log_batch', table_name='self_enrollment_email_log')
    op.drop_index('ix_email_log_link', table_name='self_enrollment_email_log')
    op.create_index(op.f('ix_self_enrollment_links_url'), 'self_enrollment_links', ['url'], unique=False)
    op.drop_index('ix_self_enroll_link_url', table_name='self_enrollment_links')
    op.create_index(op.f('ix_self_enrollment_setups_case_id'), 'self_enrollment_setups', ['case_id'], unique=False)
    op.drop_index('ix_self_enroll_setup_case', table_name='self_enrollment_setups')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_self_enroll_setup_case', 'self_enrollment_setups', ['case_id'], unique=False)
    op.drop_index(op.f('ix_self_enrollment_setups_case_id'), table_name='self_enrollment_setups')
    op.create_index('ix_self_enroll_link_url', 'self_enrollment_links', ['url'], unique=False)
    op.drop_index(op.f('ix_self_enrollment_links_url'), table_name='self_enrollment_links')
    op.create_index('ix_email_log_link', 'self_enrollment_email_log', ['link_id'], unique=False)
    op.create_index('ix_email_log_batch', 'self_enrollment_email_log', ['batch_id'], unique=False)
    op.drop_index(op.f('ix_self_enrollment_email_log_link_id'), table_name='self_enrollment_email_log')
    op.drop_index(op.f('ix_self_enrollment_email_log_batch_id'), table_name='self_enrollment_email_log')
    op.create_index('ix_self_enroll_email_batches_case', 'self_enrollment_email_batches', ['case_id'], unique=False)
    op.drop_index(op.f('ix_self_enrollment_email_batches_case_id'), table_name='self_enrollment_email_batches')
    op.create_index('ix_product_criteria_product', 'products_gi_criteria', ['product_id'], unique=False)
    op.drop_index(op.f('ix_products_gi_criteria_product_id'), table_name='products_gi_criteria')
    op.create_index('ix_products_gi_bypass_questions_product', 'products_gi_bypass_questions', ['product_id'], unique=False)
    op.drop_index(op.f('ix_products_gi_bypass_questions_product_id'), table_name='products_gi_bypass_questions')
    op.create_index('ix_form_template_tabs_template', 'form_template_tabs', ['form_template_id'], unique=False)
    op.drop_index(op.f('ix_form_template_tabs_form_template_id'), table_name='form_template_tabs')
    op.create_index('ix_enrollment_batches_hash', 'enrollment_import_batches', ['log_hash'], unique=False)
    op.create_index('ix_enrollment_batches_case', 'enrollment_import_batches', ['case_token'], unique=False)
    op.drop_index(op.f('ix_enrollment_import_batches_log_hash'), table_name='enrollment_import_batches')
    op.drop_index(op.f('ix_enrollment_import_batches_case_token'), table_name='enrollment_import_batches')
    op.create_index('ix_enrollment_batch_items_batch', 'enrollment_import_batch_items', ['enrollment_batch_id'], unique=False)
    op.drop_index(op.f('ix_enrollment_import_batch_items_enrollment_batch_id'), table_name='enrollment_import_batch_items')
    op.create_index('ix_enrollment_applications_census_record', 'enrollment_applications', ['census_record_id'], unique=False)
    op.create_index('ix_enrollment_applications_case', 'enrollment_applications', ['case_id'], unique=False)
    op.drop_index(op.f('ix_enrollment_applications_census_record_id'), table_name='enrollment_applications')
    op.drop_index(op.f('ix_enrollment_applications_case_id'), table_name='enrollment_applications')
    op.create_index('ix_enrollment_app_coverages_enrollment_id', 'enrollment_application_coverage', ['enrollment_application_id'], unique=False)
    op.drop_index(op.f('ix_enrollment_application_coverage_enrollment_application_id'), table_name='enrollment_application_coverage')
    op.create_index('ix_cases_token', 'cases', ['case_token'], unique=True)
    op.drop_index(op.f('ix_cases_case_token'), table_name='cases')
    op.create_index('ix_cases_product_product', 'case_products', ['product_id'], unique=False)
    op.create_index('ix_case_enrollment_periods_case', 'case_enrollment_periods', ['case_id'], unique=False)
    op.drop_index(op.f('ix_case_enrollment_periods_case_id'), table_name='case_enrollment_periods')
    op.create_index('ix_case_census_records_case', 'case_census', ['case_id'], unique=False)
    op.drop_index(op.f('ix_case_census_case_id'), table_name='case_census')
    op.create_index('ix_api_tokens_url', 'api_tokens', ['stormpath_url'], unique=False)
    op.create_index('ix_api_tokens_token', 'api_tokens', ['api_token'], unique=True)
    op.drop_index(op.f('ix_api_tokens_stormpath_url'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_api_token'), table_name='api_tokens')
    op.create_index('ix_agents_url', 'agents', ['stormpath_url'], unique=True)
    op.create_index('ix_agents_code', 'agents', ['agent_code'], unique=False)
    op.drop_index(op.f('ix_agents_stormpath_url'), table_name='agents')
    op.drop_index(op.f('ix_agents_agent_code'), table_name='agents')
    ### end Alembic commands ###
