"""adding recipient role to template tas

Revision ID: 17ccfb61490c
Revises: 37a4237baa84
Create Date: 2015-08-01 19:06:05.982951

"""

# revision identifiers, used by Alembic.
revision = '17ccfb61490c'
down_revision = '37a4237baa84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_template_tabs', sa.Column('recipient_role', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_template_tabs', 'recipient_role')
    ### end Alembic commands ###
