"""adding partner agents table

Revision ID: 19fafb37b171
Revises: 4ab0230255e2
Create Date: 2015-01-14 04:20:56.814777

"""

# revision identifiers, used by Alembic.
revision = '19fafb37b171'
down_revision = '4ab0230255e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_partner_agents',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('case_id', 'agent_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_partner_agents')
    ### end Alembic commands ###
