"""added phone numbers to census

Revision ID: 1b34853771fb
Revises: 523578c734b9
Create Date: 2014-10-28 01:02:06.827075

"""

# revision identifiers, used by Alembic.
revision = '1b34853771fb'
down_revision = '523578c734b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_census', sa.Column('employee_phone', sa.String(length=32), nullable=True))
    op.add_column('case_census', sa.Column('spouse_phone', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_census', 'spouse_phone')
    op.drop_column('case_census', 'employee_phone')
    ### end Alembic commands ###
