"""Adding columns for Okta id

Revision ID: 1be4242481d2
Revises: 435b9aac818d
Create Date: 2017-06-21 03:56:02.430947

"""

# revision identifiers, used by Alembic.
revision = '1be4242481d2'
down_revision = '435b9aac818d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('okta_id', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('username', sa.String(), nullable=True))
    op.create_index(op.f('ix_agents_okta_id'), 'agents', ['okta_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_okta_id'), table_name='agents')
    op.drop_column('agents', 'username')
    op.drop_column('agents', 'okta_id')
    ### end Alembic commands ###
