"""empty message

Revision ID: 1dd6ec928db9
Revises: 214e18d30f8a
Create Date: 2016-01-07 20:38:43.788157

"""

# revision identifiers, used by Alembic.
revision = '1dd6ec928db9'
down_revision = '214e18d30f8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_split_setups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('commision_subcount_code', sa.String(), server_default='', nullable=True),
    sa.Column('split_percentage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_split_setups_case_id'), 'agent_split_setups', ['case_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_split_setups_case_id'), table_name='agent_split_setups')
    op.drop_table('agent_split_setups')
    ### end Alembic commands ###
