"""Tracking new tab attributes from templates for call center

Revision ID: 1f0764d8a293
Revises: 300fae40d31c
Create Date: 2016-02-08 13:29:16.362400

"""

# revision identifiers, used by Alembic.
revision = '1f0764d8a293'
down_revision = '300fae40d31c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_template_tabs', sa.Column('custom_tab_locked', sa.Boolean(), nullable=True))
    op.add_column('form_template_tabs', sa.Column('custom_tab_required', sa.Boolean(), nullable=True))
    op.add_column('form_template_tabs', sa.Column('template_tab_locked', sa.Boolean(), nullable=True))
    op.add_column('form_template_tabs', sa.Column('template_tab_required', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_template_tabs', 'template_tab_required')
    op.drop_column('form_template_tabs', 'template_tab_locked')
    op.drop_column('form_template_tabs', 'custom_tab_required')
    op.drop_column('form_template_tabs', 'custom_tab_locked')
    ### end Alembic commands ###
