"""Changed some table and column names

Revision ID: 1f8da1442eba
Revises: 284c9766488e
Create Date: 2015-01-17 03:59:53.647182

"""

# revision identifiers, used by Alembic.
revision = '1f8da1442eba'
down_revision = '284c9766488e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollment_applications', 'application_status')
    op.add_column('enrollment_applications', sa.Column('application_status', sa.Unicode(32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment_applications', sa.Column('application_status', sa.Boolean(), nullable=True))
    op.drop_column('enrollment_applications', 'application_status')
    ### end Alembic commands ###
