"""Changed column name from rider settings to product settings

Revision ID: 214e18d30f8a
Revises: 2eef59adf24d
Create Date: 2015-12-15 19:31:47.926556

"""

# revision identifiers, used by Alembic.
revision = '214e18d30f8a'
down_revision = '2eef59adf24d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('product_settings', postgresql.JSON(), nullable=True))
    op.drop_column('cases', 'case_rider_settings')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('case_rider_settings', postgresql.JSON(), autoincrement=False, nullable=True))
    op.drop_column('cases', 'product_settings')
    ### end Alembic commands ###
