"""Adding more csv columns to census record

Revision ID: 225b11a5d8d6
Revises: 595d98d9de64
Create Date: 2014-10-27 23:47:09.743068

"""

# revision identifiers, used by Alembic.
revision = '225b11a5d8d6'
down_revision = '595d98d9de64'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_census', sa.Column('child1_birthdate', sa.Date(), nullable=True))
    op.add_column('case_census', sa.Column('child1_first', sa.String(length=256), nullable=True))
    op.add_column('case_census', sa.Column('child1_last', sa.String(length=256), nullable=True))
    op.add_column('case_census', sa.Column('child2_birthdate', sa.Date(), nullable=True))
    op.add_column('case_census', sa.Column('child2_first', sa.String(length=256), nullable=True))
    op.add_column('case_census', sa.Column('child2_last', sa.String(length=256), nullable=True))
    op.add_column('case_census', sa.Column('child3_birthdate', sa.Date(), nullable=True))
    op.add_column('case_census', sa.Column('child3_first', sa.String(length=256), nullable=True))
    op.add_column('case_census', sa.Column('child3_last', sa.String(length=256), nullable=True))
    op.add_column('case_census', sa.Column('child4_birthdate', sa.Date(), nullable=True))
    op.add_column('case_census', sa.Column('child4_first', sa.String(length=256), nullable=True))
    op.add_column('case_census', sa.Column('child4_last', sa.String(length=256), nullable=True))
    op.add_column('case_census', sa.Column('child5_birthdate', sa.Date(), nullable=True))
    op.add_column('case_census', sa.Column('child5_first', sa.String(length=256), nullable=True))
    op.add_column('case_census', sa.Column('child5_last', sa.String(length=256), nullable=True))
    op.add_column('case_census', sa.Column('child6_birthdate', sa.Date(), nullable=True))
    op.add_column('case_census', sa.Column('child6_first', sa.String(length=256), nullable=True))
    op.add_column('case_census', sa.Column('child6_last', sa.String(length=256), nullable=True))
    op.add_column('case_census', sa.Column('spouse_city', sa.String(length=256), nullable=True))
    op.add_column('case_census', sa.Column('spouse_state', sa.String(length=2), nullable=True))
    op.add_column('case_census', sa.Column('spouse_street_address', sa.String(length=256), nullable=True))
    op.add_column('case_census', sa.Column('spouse_street_address2', sa.String(length=256), nullable=True))
    op.add_column('case_census', sa.Column('spouse_zip', sa.String(length=5), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_census', 'spouse_zip')
    op.drop_column('case_census', 'spouse_street_address2')
    op.drop_column('case_census', 'spouse_street_address')
    op.drop_column('case_census', 'spouse_state')
    op.drop_column('case_census', 'spouse_city')
    op.drop_column('case_census', 'child6_last')
    op.drop_column('case_census', 'child6_first')
    op.drop_column('case_census', 'child6_birthdate')
    op.drop_column('case_census', 'child5_last')
    op.drop_column('case_census', 'child5_first')
    op.drop_column('case_census', 'child5_birthdate')
    op.drop_column('case_census', 'child4_last')
    op.drop_column('case_census', 'child4_first')
    op.drop_column('case_census', 'child4_birthdate')
    op.drop_column('case_census', 'child3_last')
    op.drop_column('case_census', 'child3_first')
    op.drop_column('case_census', 'child3_birthdate')
    op.drop_column('case_census', 'child2_last')
    op.drop_column('case_census', 'child2_first')
    op.drop_column('case_census', 'child2_birthdate')
    op.drop_column('case_census', 'child1_last')
    op.drop_column('case_census', 'child1_first')
    op.drop_column('case_census', 'child1_birthdate')
    ### end Alembic commands ###
