"""renamed_enrollment_log_to_batches

Revision ID: 23470384a7b8
Revises: 429d6ff9d478
Create Date: 2015-09-15 15:14:26.420774

"""

# revision identifiers, used by Alembic.
revision = '23470384a7b8'
down_revision = '429d6ff9d478'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Unicode(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default='NOW', nullable=True),
    sa.Column('auth_token', sa.Unicode(length=64), nullable=True),
    sa.Column('case_token', sa.Unicode(length=64), nullable=True),
    sa.Column('num_processed', sa.Integer(), nullable=True),
    sa.Column('num_errors', sa.Integer(), nullable=True),
    sa.Column('log_hash', sa.Unicode(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollment_import_batch_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_batch_id', sa.Integer(), nullable=True),
    sa.Column('enrollment_record_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Unicode(length=32), nullable=True),
    sa.Column('error_message', sa.UnicodeText(), nullable=True),
    sa.Column('processed_time', sa.DateTime(), server_default='NOW', nullable=True),
    sa.ForeignKeyConstraint(['enrollment_batch_id'], ['enrollment_import_batches.id'], ),
    sa.ForeignKeyConstraint(['enrollment_record_id'], ['enrollment_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('enrollment_api_log_items')
    op.drop_table('enrollment_api_logs')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_api_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default="NOW", autoincrement=False, nullable=True),
    sa.Column('auth_token', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('case_token', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('num_processed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('num_errors', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('log_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    postgresql_ignore_search_path=False
    )
    op.create_table('enrollment_api_log_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('enrollment_log_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('enrollment_record_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_time', postgresql.TIMESTAMP(), server_default="NOW", autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['enrollment_log_id'], [u'enrollment_api_logs.id'], name=u'enrollment_api_log_items_enrollment_log_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('enrollment_import_batch_items')
    op.drop_table('enrollment_import_batches')
    ### end Alembic commands ###
