"""Add should_limit_rates_to_gi to products

Revision ID: 236e1a6732de
Revises: 325811b60b15
Create Date: 2015-10-22 18:03:29.930861

"""

# revision identifiers, used by Alembic.
revision = '236e1a6732de'
down_revision = '325811b60b15'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_custom_guaranteed_issue', sa.Column('should_limit_rates_to_gi', sa.Boolean, nullable=False, server_default=sa.text('FALSE')))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products_custom_guaranteed_issue', 'should_limit_rates_to_gi')
    ### end Alembic commands ###
