"""make created_by nullable on self enrollment setup

Revision ID: 23f9a047d797
Revises: 59b67201a4e8
Create Date: 2015-06-26 05:54:48.021646

"""

# revision identifiers, used by Alembic.
revision = '23f9a047d797'
down_revision = '59b67201a4e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('self_enrollment_setups', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('self_enrollment_setups', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
