"""Renamed criteria columns

Revision ID: 2595b8027dba
Revises: 5a7a885db111
Create Date: 2014-12-01 21:32:28.641767

"""

# revision identifiers, used by Alembic.
revision = '2595b8027dba'
down_revision = '5a7a885db111'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_gi_criteria', sa.Column('age_max', sa.Integer(), nullable=True))
    op.add_column('products_gi_criteria', sa.Column('age_min', sa.Integer(), nullable=True))
    op.add_column('products_gi_criteria', sa.Column('height_max', sa.Integer(), nullable=True))
    op.add_column('products_gi_criteria', sa.Column('height_min', sa.Integer(), nullable=True))
    op.add_column('products_gi_criteria', sa.Column('weight_max', sa.Integer(), nullable=True))
    op.add_column('products_gi_criteria', sa.Column('weight_min', sa.Integer(), nullable=True))
    op.drop_column('products_gi_criteria', 'criteria_age_min')
    op.drop_column('products_gi_criteria', 'criteria_weight_min')
    op.drop_column('products_gi_criteria', 'criteria_height_min')
    op.drop_column('products_gi_criteria', 'criteria_weight_max')
    op.drop_column('products_gi_criteria', 'criteria_height_max')
    op.drop_column('products_gi_criteria', 'criteria_age_max')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_gi_criteria', sa.Column('criteria_age_max', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products_gi_criteria', sa.Column('criteria_height_max', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products_gi_criteria', sa.Column('criteria_weight_max', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products_gi_criteria', sa.Column('criteria_height_min', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products_gi_criteria', sa.Column('criteria_weight_min', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products_gi_criteria', sa.Column('criteria_age_min', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('products_gi_criteria', 'weight_min')
    op.drop_column('products_gi_criteria', 'weight_max')
    op.drop_column('products_gi_criteria', 'height_min')
    op.drop_column('products_gi_criteria', 'height_max')
    op.drop_column('products_gi_criteria', 'age_min')
    op.drop_column('products_gi_criteria', 'age_max')
    ### end Alembic commands ###
