"""Changed some table and column names

Revision ID: 284c9766488e
Revises: 3533b639aa1f
Create Date: 2015-01-17 03:58:08.075393

"""

# revision identifiers, used by Alembic.
revision = '284c9766488e'
down_revision = '3533b639aa1f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
