"""Added new group number column for new FPP form.

Revision ID: 2de309fd0302
Revises: 42b761a58730
Create Date: 2015-03-29 01:47:13.769040

"""

# revision identifiers, used by Alembic.
revision = '2de309fd0302'
down_revision = '42b761a58730'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('group_number', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'group_number')
    ### end Alembic commands ###
