"""changing case riders to JSON settings column

Revision ID: 2eef59adf24d
Revises: 11f6fc11b5eb
Create Date: 2015-12-10 21:32:36.167955

"""

# revision identifiers, used by Alembic.
revision = '2eef59adf24d'
down_revision = '11f6fc11b5eb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('case_rider_settings', postgresql.JSON(), nullable=True))
    op.drop_column('cases', 'case_riders')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('case_riders', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('cases', 'case_rider_settings')
    ### end Alembic commands ###
