"""add call center flag to case

Revision ID: 300fae40d31c
Revises: 53d9856f980d
Create Date: 2016-01-28 22:09:43.587210

"""

# revision identifiers, used by Alembic.
revision = '300fae40d31c'
down_revision = '53d9856f980d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('should_use_call_center_workflow', sa.Boolean(), server_default='FALSE', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'should_use_call_center_workflow')
    ### end Alembic commands ###
