"""Creating enrollment records and coverage records along with any other tweaks to census data

Revision ID: 31523a310f8f
Revises: 19fafb37b171
Create Date: 2015-01-14 19:37:37.241369

"""

# revision identifiers, used by Alembic.
revision = '31523a310f8f'
down_revision = '19fafb37b171'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_census', sa.Column('is_uploaded_census', sa.Boolean(), server_default='TRUE', nullable=True))
    op.alter_column('case_census', 'case_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default='0')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case_census', 'case_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default='0')
    op.drop_column('case_census', 'is_uploaded_census')
    ### end Alembic commands ###
