"""Add bank draft form option to case setup

Revision ID: 325811b60b15
Revises: 2df041cc5fff
Create Date: 2015-10-02 17:48:07.643502

"""

# revision identifiers, used by Alembic.
revision = '325811b60b15'
down_revision = '2df041cc5fff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('include_bank_draft_form', sa.Boolean(), server_default='FALSE', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'include_bank_draft_form')
    ### end Alembic commands ###
