"""add email log status

Revision ID: 3483eb9991a1
Revises: a0d114586a9
Create Date: 2015-06-20 04:26:00.640126

"""

# revision identifiers, used by Alembic.
revision = '3483eb9991a1'
down_revision = 'a0d114586a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('self_enrollment_email_log', sa.Column('status', sa.Unicode(length=16), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('self_enrollment_email_log', 'status')
    ### end Alembic commands ###
