"""add download restriction

Revision ID: 370108254ac
Revises: 2fc712362050
Create Date: 2015-09-02 13:45:39.686008

"""

# revision identifiers, used by Alembic.
revision = '370108254ac'
down_revision = '2fc712362050'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('can_partners_download_enrollments', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'can_partners_download_enrollments')
    ### end Alembic commands ###
