"""Add json fields to enrollment_applications to capture raw and standardized import data

Revision ID: 37a4237baa84
Revises: 4ede3fd0f497
Create Date: 2015-07-29 20:55:28.311950

"""

# revision identifiers, used by Alembic.
revision = '37a4237baa84'
down_revision = '4ede3fd0f497'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment_applications', sa.Column('received_data', postgresql.JSON(), nullable=True))
    op.add_column('enrollment_applications', sa.Column('standardized_data', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollment_applications', 'standardized_data')
    op.drop_column('enrollment_applications', 'received_data')
    ### end Alembic commands ###
