"""Many to many application and submissions

Revision ID: 3918b7c2f45f
Revises: 3c3815fe2e09
Create Date: 2016-03-29 13:29:36.134603

"""

# revision identifiers, used by Alembic.
revision = '3918b7c2f45f'
down_revision = '3c3815fe2e09'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_application_submissions',
    sa.Column('enrollment_application_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_submission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_application_id'], ['enrollment_applications.id'], ),
    sa.ForeignKeyConstraint(['enrollment_submission_id'], ['enrollment_submissions.id'], ),
    sa.PrimaryKeyConstraint('enrollment_application_id', 'enrollment_submission_id')
    )
    op.add_column(u'enrollment_submissions', sa.Column('created_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True))
    op.add_column(u'enrollment_submissions', sa.Column('data', sa.UnicodeText(), nullable=True))
    op.add_column(u'enrollment_submissions', sa.Column('submission_type', sa.Unicode(length=32), nullable=True))
    op.drop_constraint(u'enrollment_submissions_enrollment_application_id_fkey', 'enrollment_submissions', type_='foreignkey')
    op.drop_column(u'enrollment_submissions', 'enrollment_application_id')
    op.drop_column(u'enrollment_submissions', 'processing_time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'enrollment_submissions', sa.Column('processing_time', postgresql.TIMESTAMP(), server_default=sa.text(u'now()'), autoincrement=False, nullable=True))
    op.add_column(u'enrollment_submissions', sa.Column('enrollment_application_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'enrollment_submissions_enrollment_application_id_fkey', 'enrollment_submissions', 'enrollment_applications', ['enrollment_application_id'], ['id'])
    op.drop_column(u'enrollment_submissions', 'submission_type')
    op.drop_column(u'enrollment_submissions', 'data')
    op.drop_column(u'enrollment_submissions', 'created_at')
    op.drop_table('enrollment_application_submissions')
    ### end Alembic commands ###
