"""added error_message column to summary_confirmation_email_logs

Revision ID: 3a8e14db71ea
Revises: bae868f8111f
Create Date: 2016-07-22 14:43:43.341319

"""

# revision identifiers, used by Alembic.
revision = '3a8e14db71ea'
down_revision = 'bae868f8111f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summary_confirmation_email_log', sa.Column('error_message', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summary_confirmation_email_log', 'error_message')
    ### end Alembic commands ###
