"""Adding in enrollment_submissions and submission_logs tables

Revision ID: 3c3815fe2e09
Revises: 85c1dfc608a1
Create Date: 2016-03-28 09:14:32.435184

"""

# revision identifiers, used by Alembic.
revision = '3c3815fe2e09'
down_revision = '85c1dfc608a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_application_id', sa.Integer(), nullable=True),
    sa.Column('processing_time', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('status', sa.Unicode(length=32), server_default=u'pending', nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_application_id'], ['enrollment_applications.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_submission_id', sa.Integer(), nullable=True),
    sa.Column('processing_time', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('status', sa.Unicode(length=32), server_default=u'success', nullable=True),
    sa.Column('message', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_submission_id'], ['enrollment_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission_logs')
    op.drop_table('enrollment_submissions')
    ### end Alembic commands ###
