"""Add restricted agents table

Revision ID: 3cea481a88e1
Revises: 24d2a377ae6e
Create Date: 2015-01-29 04:01:18.442270

"""

# revision identifiers, used by Alembic.
revision = '3cea481a88e1'
down_revision = '24d2a377ae6e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_restricted_agents',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'agent_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_restricted_agents')
    ### end Alembic commands ###
