"""add self-enrollment table and tie to cases, add link table

Revision ID: 411f89d64846
Revises: 536f64a850
Create Date: 2015-06-15 19:28:23.181140

"""

# revision identifiers, used by Alembic.
revision = '411f89d64846'
down_revision = '536f64a850'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('self_enrollment_setups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('self_enrollment_type', sa.Unicode(length=16), nullable=False),
    sa.Column('use_email', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('email_sender_name', sa.Unicode(), nullable=True),
    sa.Column('email_sender_email', sa.Unicode(), nullable=True),
    sa.Column('email_subject', sa.Unicode(), nullable=True),
    sa.Column('email_message', sa.UnicodeText(), nullable=True),
    sa.Column('use_landing_page', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('page_title', sa.Unicode(), nullable=True),
    sa.Column('page_text', sa.UnicodeText(), nullable=True),
    sa.Column('page_disclaimer', sa.UnicodeText(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('self_enrollment_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('census_record_id', sa.Integer(), nullable=True),
    sa.Column('self_enrollment_setup_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Unicode(length=2000), nullable=False),
    sa.Column('clicks', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['census_record_id'], ['case_census.id'], ),
    sa.ForeignKeyConstraint(['self_enrollment_setup_id'], ['self_enrollment_setups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'cases', sa.Column('is_self_enrollment', sa.Boolean(), server_default='FALSE', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'cases', 'is_self_enrollment')
    op.drop_table('self_enrollment_links')
    op.drop_table('self_enrollment_setups')
    ### end Alembic commands ###
