"""Added new GI product tables

Revision ID: 4274968f00fe
Revises: 51bef3dd2227
Create Date: 2014-11-16 00:23:04.402292

"""

# revision identifiers, used by Alembic.
revision = '4274968f00fe'
down_revision = '51bef3dd2227'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_agents',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'agent_id')
    )
    op.create_table('products_custom_guaranteed_issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_product_id', sa.Integer(), nullable=True),
    sa.Column('guarantee_issue_amount', sa.Integer(), nullable=True),
    sa.Column('criteria_age_min', sa.Integer(), nullable=True),
    sa.Column('criteria_age_max', sa.Integer(), nullable=True),
    sa.Column('criteria_height_min', sa.Integer(), nullable=True),
    sa.Column('criteria_height_max', sa.Integer(), nullable=True),
    sa.Column('criteria_weight_min', sa.Integer(), nullable=True),
    sa.Column('criteria_weight_max', sa.Integer(), nullable=True),
    sa.Column('statement_of_health_bypass_type', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['base_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'products', sa.Column('product_type', sa.String(length=16), server_default=u'base', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'products', 'product_type')
    op.drop_table('products_custom_guaranteed_issue')
    op.drop_table('product_agents')
    ### end Alembic commands ###
