"""Adding ordinal to case_products relation table.

Revision ID: 429ac64df4f7
Revises: 22f640bc441b
Create Date: 2016-02-23 14:35:30.006016

"""

# revision identifiers, used by Alembic.
revision = '429ac64df4f7'
down_revision = '22f640bc441b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_products', sa.Column('ordinal', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_products', 'ordinal')
    ### end Alembic commands ###
