"""Created a table to track status of each imported enrollment

Revision ID: 429d6ff9d478
Revises: 1f0e6013e4d7
Create Date: 2015-09-14 15:45:24.738171

"""

# revision identifiers, used by Alembic.
revision = '429d6ff9d478'
down_revision = '1f0e6013e4d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_api_log_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_log_id', sa.Integer(), nullable=True),
    sa.Column('enrollment_record_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Unicode(length=32), nullable=True),
    sa.Column('error_message', sa.UnicodeText(), nullable=True),
    sa.Column('processed_time', sa.DateTime(), server_default='NOW', nullable=True),
    sa.ForeignKeyConstraint(['enrollment_log_id'], ['enrollment_api_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment_api_log_items')
    ### end Alembic commands ###
