"""Added height, weight, smoker for emp and sospouse on census

Revision ID: 42b761a58730
Revises: 39c9bb10de2
Create Date: 2015-02-21 03:05:45.999399

"""

# revision identifiers, used by Alembic.
revision = '42b761a58730'
down_revision = '39c9bb10de2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_census', sa.Column('employee_height_inches', sa.String(length=16), nullable=True))
    op.add_column('case_census', sa.Column('employee_smoker', sa.String(length=8), nullable=True))
    op.add_column('case_census', sa.Column('employee_weight_lbs', sa.String(length=16), nullable=True))
    op.add_column('case_census', sa.Column('spouse_height_inches', sa.String(length=16), nullable=True))
    op.add_column('case_census', sa.Column('spouse_smoker', sa.String(length=8), nullable=True))
    op.add_column('case_census', sa.Column('spouse_weight_lbs', sa.String(length=16), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_census', 'spouse_weight_lbs')
    op.drop_column('case_census', 'spouse_smoker')
    op.drop_column('case_census', 'spouse_height_inches')
    op.drop_column('case_census', 'employee_weight_lbs')
    op.drop_column('case_census', 'employee_smoker')
    op.drop_column('case_census', 'employee_height_inches')
    ### end Alembic commands ###
