"""Adding user groups to database

Revision ID: 435b9aac818d
Revises: 20845f9fe03f
Create Date: 2017-05-22 17:51:51.372056

"""

# revision identifiers, used by Alembic.
revision = '435b9aac818d'
down_revision = '6119d6ceef97'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('group', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_groups_agent_id'), 'agent_groups', ['agent_id'], unique=False)
    op.add_column(u'agents', sa.Column('custom_data', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'agents', 'custom_data')
    op.drop_index(op.f('ix_agent_groups_agent_id'), table_name='agent_groups')
    op.drop_table('agent_groups')
    ### end Alembic commands ###
