"""Add Enrollment Log table

Revision ID: 44c62ed2572a
Revises: 17ccfb61490c
Create Date: 2015-08-03 18:10:53.667453

"""

# revision identifiers, used by Alembic.
revision = '44c62ed2572a'
down_revision = '17ccfb61490c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_api_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Unicode(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default='NOW', nullable=True),
    sa.Column('auth_token', sa.Unicode(length=64), nullable=True),
    sa.Column('case_token', sa.Unicode(length=64), nullable=True),
    sa.Column('num_processed', sa.Integer(), nullable=True),
    sa.Column('num_errors', sa.Integer(), nullable=True),
    sa.Column('log_hash', sa.Unicode(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment_api_logs')
    ### end Alembic commands ###
