"""Added foreign key

Revision ID: 44cf9c4873ae
Revises: 4c388f5dfcff
Create Date: 2014-10-17 17:37:58.456058

"""

# revision identifiers, used by Alembic.
revision = '44cf9c4873ae'
down_revision = '4c388f5dfcff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_case_census_cases', "case_census", "cases", ["case_id"], ["id"])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_case_census_cases', 'case_census')
    ### end Alembic commands ###
