"""add docusign template tables

Revision ID: 44e02491e27
Revises: 58bb52782fb7
Create Date: 2015-07-16 06:55:57.265404

"""

# revision identifiers, used by Alembic.
revision = '44e02491e27'
down_revision = '58bb52782fb7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Unicode(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_templates_tabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_template_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('type_', sa.Unicode(), nullable=True),
    sa.Column('label', sa.Unicode(), nullable=True),
    sa.Column('is_bold', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.Column('is_italic', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.Column('is_underline', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.Column('custom_type', sa.Unicode(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('font', sa.Unicode(), nullable=True),
    sa.Column('font_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['form_template_id'], ['form_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_templates_tabs')
    op.drop_table('form_templates')
    ### end Alembic commands ###
