"""made flat fee nullable so initialize_db works

Revision ID: 49198e172f43
Revises: 0b9c9ffe6fb2
Create Date: 2016-05-06 21:39:55.998113

"""

# revision identifiers, used by Alembic.
revision = '49198e172f43'
down_revision = '0b9c9ffe6fb2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case_census', 'employee_zip',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('case_census', 'spouse_zip',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('products', 'flat_fee',
               existing_type=sa.NUMERIC(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('products', 'flat_fee',
    #            existing_type=sa.NUMERIC(),
    #            nullable=False)
    op.alter_column('case_census', 'spouse_zip',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('case_census', 'employee_zip',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    ### end Alembic commands ###
