"""adding creation date to cases

Revision ID: 4ab0230255e2
Revises: 2595b8027dba
Create Date: 2015-01-14 02:45:01.913168

"""

# revision identifiers, used by Alembic.
revision = '4ab0230255e2'
down_revision = '2595b8027dba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('created_date', sa.DateTime(), server_default='NOW', nullable=True))
    op.alter_column('cases', 'agent_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default='1')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'agent_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default='1')
    op.drop_column('cases', 'created_date')
    ### end Alembic commands ###
