"""Added foreign key to case census records

Revision ID: 4c388f5dfcff
Revises: 5120ebf1c1cc
Create Date: 2014-10-17 17:15:49.846151

"""

# revision identifiers, used by Alembic.
revision = '4c388f5dfcff'
down_revision = '5120ebf1c1cc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # Adjust to not nullable
    op.add_column('case_census', sa.Column('case_id', sa.Integer(), nullable=False, 
                                           server_default=sa.DefaultClause("0")))
    #case_census_case_id = table('case_census', column('case_id'))
    #op.execute(case_census_case_id.update().values(case_id=0))
    #op.alter_column('case_census', 'case_id', nullable=False, 
    #                server_default=sa.DefaultClause("0"))
    
    op.alter_column('cases', 'agent_id',
               existing_type=sa.INTEGER(),
               #nullable=False,
               server_default=sa.DefaultClause("1"))
    op.alter_column('cases', 'agent_id',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    #server_default=sa.DefaultClause("1")
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'agent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('case_census', 'case_id')
    ### end Alembic commands ###
