"""Adding customer shortname to product

Revision ID: 4d829827e13b
Revises: 2a4c2de08d5c
Create Date: 2016-02-15 16:19:07.725400

"""

# revision identifiers, used by Alembic.
revision = '4d829827e13b'
down_revision = '2a4c2de08d5c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('customer_short_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'customer_short_name')
    ### end Alembic commands ###
