"""added effective date column to enrollment applications

Revision ID: 4d944fc3f838
Revises: 82d7eaf74f9d
Create Date: 2016-07-18 20:16:32.251357

"""

# revision identifiers, used by Alembic.
revision = '4d944fc3f838'
down_revision = '82d7eaf74f9d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment_applications', sa.Column('effective_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollment_applications', 'effective_date')
    ### end Alembic commands ###
