"""Indexing a few key columns to speed up execution of enrollment query

Revision ID: 4f0bb7d9b9ad
Revises: 429ac64df4f7
Create Date: 2016-02-26 10:04:58.595295

"""

# revision identifiers, used by Alembic.
revision = '4f0bb7d9b9ad'
down_revision = '429ac64df4f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_enrollment_applications_agent_case', 'enrollment_applications', ['agent_id', 'case_id'], unique=False)
    op.create_index(op.f('ix_self_enrollment_email_log_census_id'), 'self_enrollment_email_log', ['census_id'], unique=False)
    op.create_index(op.f('ix_self_enrollment_email_log_status'), 'self_enrollment_email_log', ['status'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_self_enrollment_email_log_status'), table_name='self_enrollment_email_log')
    op.drop_index(op.f('ix_self_enrollment_email_log_census_id'), table_name='self_enrollment_email_log')
    op.drop_index('ix_enrollment_applications_agent_case', table_name='enrollment_applications')
    ### end Alembic commands ###
