"""Add use_base_product_settings

Revision ID: 4f7abbcbac0f
Revises: 4d829827e13b
Create Date: 2016-02-17 15:32:17.938716

"""

# revision identifiers, used by Alembic.
revision = '4f7abbcbac0f'
down_revision = '4d829827e13b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('use_base_product_settings', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'use_base_product_settings')
    ### end Alembic commands ###
