"""add signature method column to enrollment

Revision ID: 5078ce7cc7ac
Revises: b4be94f5565c
Create Date: 2016-05-28 15:11:43.898943

"""

# revision identifiers, used by Alembic.
revision = '5078ce7cc7ac'
down_revision = 'b4be94f5565c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment_applications', sa.Column('signature_method', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollment_applications', 'signature_method')
    ### end Alembic commands ###
