"""Add Omit AAW to Case

Revision ID: 509b0b9ad6a7
Revises: 85c1dfc608a1
Create Date: 2016-04-15 12:11:45.376253

"""

# revision identifiers, used by Alembic.
revision = '509b0b9ad6a7'
down_revision = '85c1dfc608a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('omit_actively_at_work', sa.Boolean(), server_default='FALSE', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'omit_actively_at_work')
    ### end Alembic commands ###
