"""Increase size of agent code field

Revision ID: 5120ebf1c1cc
Revises: 54e3eeecf645
Create Date: 2014-10-16 16:30:33.342678

"""

# revision identifiers, used by Alembic.
revision = '5120ebf1c1cc'
down_revision = '54e3eeecf645'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'agent_code', type_=sa.String(length=32))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'agent_code', type_=sa.String(length=5))
    ### end Alembic commands ###
