"""add self-enrollment email log table

Revision ID: 51a3684ca671
Revises: 411f89d64846
Create Date: 2015-06-16 19:11:05.674326

"""

# revision identifiers, used by Alembic.
revision = '51a3684ca671'
down_revision = '411f89d64846'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('self_enrollment_email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('census_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('sent_date', sa.DateTime(), nullable=False),
    sa.Column('email_to_address', sa.Unicode(), nullable=True),
    sa.Column('email_to_name', sa.Unicode(), nullable=True),
    sa.Column('email_from_address', sa.Unicode(), nullable=True),
    sa.Column('email_from_name', sa.Unicode(), nullable=True),
    sa.Column('email_subject', sa.Unicode(), nullable=True),
    sa.Column('email_body', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['census_id'], ['case_census.id'], ),
    sa.ForeignKeyConstraint(['link_id'], ['self_enrollment_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('self_enrollment_email_log')
    ### end Alembic commands ###
