"""Added gender to census

Revision ID: 51bef3dd2227
Revises: 1b34853771fb
Create Date: 2014-10-28 01:35:45.631030

"""

# revision identifiers, used by Alembic.
revision = '51bef3dd2227'
down_revision = '1b34853771fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_census', sa.Column('employee_gender', sa.String(length=6), nullable=True))
    op.add_column('case_census', sa.Column('spouse_gender', sa.String(length=6), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_census', 'spouse_gender')
    op.drop_column('case_census', 'employee_gender')
    ### end Alembic commands ###
