"""Remove redundant column

Revision ID: 523578c734b9
Revises: 225b11a5d8d6
Create Date: 2014-10-27 23:47:50.269429

"""

# revision identifiers, used by Alembic.
revision = '523578c734b9'
down_revision = '225b11a5d8d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_census', 'spouse_address')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_census', sa.Column('spouse_address', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    ### end Alembic commands ###
