"""Added a second signing column for applicant

Revision ID: 53d9856f980d
Revises: 379bcdb25e24
Create Date: 2016-01-22 16:37:39.051392

"""

# revision identifiers, used by Alembic.
revision = '53d9856f980d'
down_revision = '379bcdb25e24'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment_applications', sa.Column('agent_signing_status', sa.Unicode(length=32), nullable=True))
    op.add_column('enrollment_applications', sa.Column('applicant_signing_status', sa.Unicode(length=32), nullable=True))
    op.drop_column('enrollment_applications', 'signing_status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment_applications', sa.Column('signing_status', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_column('enrollment_applications', 'applicant_signing_status')
    op.drop_column('enrollment_applications', 'agent_signing_status')
    ### end Alembic commands ###
