"""Adding Self Enrollment Email batch table and columns.

Revision ID: 54c74718997d
Revises: 4207ba1a44fc
Create Date: 2015-07-01 18:37:25.976518

"""

# revision identifiers, used by Alembic.
revision = '54c74718997d'
down_revision = '4207ba1a44fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('self_enrollment_email_batches', sa.Column('case_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'self_enrollment_email_batches', 'cases', ['case_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('self_enrollment_email_batches', 'case_id')
    ### end Alembic commands ###
