"""Initial commit

Revision ID: 54e3eeecf645
Revises: None
Create Date: 2014-10-16 14:35:52.401801

"""

# revision identifiers, used by Alembic.
revision = '54e3eeecf645'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_code', sa.String(length=5), nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('first', sa.String(), nullable=True),
    sa.Column('last', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('stormpath_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_census',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('employee_ssn', sa.String(length=9), nullable=True),
    sa.Column('employee_first', sa.String(length=256), nullable=True),
    sa.Column('employee_last', sa.String(length=256), nullable=True),
    sa.Column('employee_birthdate', sa.Date(), nullable=True),
    sa.Column('employee_street_address', sa.String(length=256), nullable=True),
    sa.Column('employee_street_address2', sa.String(length=256), nullable=True),
    sa.Column('employee_city', sa.String(length=256), nullable=True),
    sa.Column('employee_state', sa.String(length=2), nullable=True),
    sa.Column('employee_zip', sa.String(length=9), nullable=True),
    sa.Column('employee_email', sa.String(length=256), nullable=True),
    sa.Column('spouse_ssn', sa.String(length=9), nullable=True),
    sa.Column('spouse_first', sa.String(length=256), nullable=True),
    sa.Column('spouse_last', sa.String(length=256), nullable=True),
    sa.Column('spouse_address', sa.String(length=512), nullable=True),
    sa.Column('spouse_birthdate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('situs_state', sa.String(length=2), nullable=False),
    sa.Column('situs_city', sa.String(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_products',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('case_id', 'product_id')
    )
    op.create_table('case_enrollment_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('period_type', sa.String(length=32), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_enrollment_periods')
    op.drop_table('case_products')
    op.drop_table('cases')
    op.drop_table('case_census')
    op.drop_table('agents')
    op.drop_table('products')
    ### end Alembic commands ###
