"""added a created date to enrollment applications.

Revision ID: 58b1756eb01e
Revises: a1857d7f221d
Create Date: 2016-12-05 16:15:20.148103

"""

# revision identifiers, used by Alembic.
revision = '58b1756eb01e'
down_revision = 'a1857d7f221d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment_applications', sa.Column('created_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_enrollment_applications_created_time'), 'enrollment_applications', ['created_time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollment_applications_created_time'), table_name='enrollment_applications')
    op.drop_column('enrollment_applications', 'created_time')
    ### end Alembic commands ###
