"""Added enrollment period type to case

Revision ID: 595d98d9de64
Revises: 499a213c2399
Create Date: 2014-10-26 03:35:17.427504

"""

# revision identifiers, used by Alembic.
revision = '595d98d9de64'
down_revision = '499a213c2399'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('enrollment_period_type', sa.String(length=16), nullable=True))
    op.alter_column('cases', 'situs_state',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'situs_state',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.drop_column('cases', 'enrollment_period_type')
    ### end Alembic commands ###
