"""Fixed datetime columns to use proper function form of NOW() rather than use table creation time

Revision ID: 5aebb1c81132
Revises: 23470384a7b8
Create Date: 2015-09-29 20:13:38.224711

"""

# revision identifiers, used by Alembic.
revision = '5aebb1c81132'
down_revision = '23470384a7b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.alter_column('enrollment_import_batches', 'timestamp', server_default=sa.text('CURRENT_DATE'))
    op.alter_column('enrollment_import_batch_items', 'processed_time', server_default=sa.text('CURRENT_DATE'))
    op.alter_column('case_census', 'upload_date', server_default=sa.text('CURRENT_DATE'))


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
