"""Added premium amount to GI criteria

Revision ID: 5bbb4335a759
Revises: 58b1756eb01e
Create Date: 2017-01-23 14:34:03.306019

"""

# revision identifiers, used by Alembic.
revision = '5bbb4335a759'
down_revision = '58b1756eb01e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_gi_criteria', sa.Column('guarantee_issue_premium', sa.Numeric(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products_gi_criteria', 'guarantee_issue_premium')
    ### end Alembic commands ###
