"""Census record occupation class is now defaulted to 'Default' and is not nullable.

Revision ID: 5d7c95e280
Revises: 33d857a70c39
Create Date: 2016-03-31 16:32:17.153350

"""

# revision identifiers, used by Alembic.
revision = '5d7c95e280'
down_revision = '33d857a70c39'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("""UPDATE case_census SET occupation_class = 'Default' WHERE occupation_class IS NULL""")
    op.alter_column('case_census', 'occupation_class',
               existing_type=sa.VARCHAR(length=256),
               nullable=False, server_default=sa.DefaultClause('Default'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case_census', 'occupation_class',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.execute("""ALTER TABLE case_census ALTER COLUMN occupation_class DROP DEFAULT""")
    ### end Alembic commands ###
