"""added case_id to export table

Revision ID: 72600a788388
Revises: c3b655d2a87d
Create Date: 2016-06-23 19:23:03.894848

"""

# revision identifiers, used by Alembic.
revision = '72600a788388'
down_revision = 'c3b655d2a87d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('params', postgresql.JSON(), nullable=True),
    sa.Column('user_href', sa.UnicodeText(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.UnicodeText(), nullable=True),
    sa.Column('download_type', sa.UnicodeText(), nullable=True),
    sa.Column('unicode_data', sa.UnicodeText(), nullable=True),
    sa.Column('binary_data', sa.Binary(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('background_exports')
    ### end Alembic commands ###
