"""Flat Fee default

Revision ID: 72a680ebb6ad
Revises: 99bdcd3053e7
Create Date: 2016-05-03 15:14:28.786090

"""

# revision identifiers, used by Alembic.
revision = '72a680ebb6ad'
down_revision = '99bdcd3053e7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(text('UPDATE products SET flat_fee = 5.00 WHERE flat_fee is NULL'))
    op.alter_column('products', 'flat_fee',
               existing_type=sa.NUMERIC(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'flat_fee',
               existing_type=sa.NUMERIC(),
               nullable=True)
    ### end Alembic commands ###
