"""Add summary_confirmation_email_log table

Revision ID: 80c3571eb423
Revises: 72600a788388
Create Date: 2016-07-21 18:07:19.039828

"""

# revision identifiers, used by Alembic.
revision = '80c3571eb423'
down_revision = '72600a788388'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'effective_date_settings')
    op.drop_column('cases', 'ongoing_enrollment_type')
    op.drop_column('cases', 'open_enrollment_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('open_enrollment_type', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('ongoing_enrollment_type', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('effective_date_settings', postgresql.JSON(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
