"""fix problems

Revision ID: 84ff80a218a2
Revises: db0671175670
Create Date: 2016-07-22 19:25:16.059303

"""

# revision identifiers, used by Alembic.
revision = '84ff80a218a2'
down_revision = 'db0671175670'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('effective_date_settings', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'effective_date_settings')
    ### end Alembic commands ###
