"""Added indexes to census table to speed up server-side pagination and searching

Revision ID: 85c1dfc608a1
Revises: 4f0bb7d9b9ad
Create Date: 2016-03-02 10:55:59.129335

"""

# revision identifiers, used by Alembic.
revision = '85c1dfc608a1'
down_revision = '4f0bb7d9b9ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_case_census_employee_email'), 'case_census', ['employee_email'], unique=False)
    op.create_index(op.f('ix_case_census_employee_first'), 'case_census', ['employee_first'], unique=False)
    op.create_index(op.f('ix_case_census_employee_last'), 'case_census', ['employee_last'], unique=False)
    op.create_index(op.f('ix_case_census_employee_ssn'), 'case_census', ['employee_ssn'], unique=False)
    op.create_index(op.f('ix_enrollment_applications_docusign_envelope_id'), 'enrollment_applications', ['docusign_envelope_id'], unique=False)
    op.create_index(op.f('ix_enrollment_applications_signature_time'), 'enrollment_applications', ['signature_time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollment_applications_signature_time'), table_name='enrollment_applications')
    op.drop_index(op.f('ix_enrollment_applications_docusign_envelope_id'), table_name='enrollment_applications')
    op.drop_index(op.f('ix_case_census_employee_ssn'), table_name='case_census')
    op.drop_index(op.f('ix_case_census_employee_last'), table_name='case_census')
    op.drop_index(op.f('ix_case_census_employee_first'), table_name='case_census')
    op.drop_index(op.f('ix_case_census_employee_email'), table_name='case_census')
    ### end Alembic commands ###
