"""remove error message column

Revision ID: 8be7d74a0438
Revises: 3a8e14db71ea
Create Date: 2016-07-22 16:05:52.627522

"""

# revision identifiers, used by Alembic.
revision = '8be7d74a0438'
down_revision = '3a8e14db71ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summary_confirmation_email_log', 'error_message')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summary_confirmation_email_log', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
