"""Added index to submission logs

Revision ID: a1857d7f221d
Revises: da452280ac3b
Create Date: 2016-09-16 14:40:56.681345

"""

# revision identifiers, used by Alembic.
revision = 'a1857d7f221d'
down_revision = 'da452280ac3b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_submission_logs_enrollment_submission_id'), 'submission_logs', ['enrollment_submission_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_logs_enrollment_submission_id'), table_name='submission_logs')
    ### end Alembic commands ###
