"""moving effective date column to enrollment_application_coverage

Revision ID: ac7812ef81a0
Revises: 4d944fc3f838
Create Date: 2016-07-19 16:51:43.683249

"""

# revision identifiers, used by Alembic.
revision = 'ac7812ef81a0'
down_revision = '4d944fc3f838'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment_application_coverage', sa.Column('effective_date', sa.DateTime(), nullable=True))
    op.drop_column('enrollment_applications', 'effective_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment_applications', sa.Column('effective_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('enrollment_application_coverage', 'effective_date')
    ### end Alembic commands ###
