"""Case Paylogix

Revision ID: b4be94f5565c
Revises: fe8c6559b031
Create Date: 2016-05-11 15:18:01.585756

"""

# revision identifiers, used by Alembic.
revision = 'b4be94f5565c'
down_revision = 'fe8c6559b031'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('requires_paylogix_export', sa.Boolean(), server_default='FALSE', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'requires_paylogix_export')
    ### end Alembic commands ###
