"""Adding missing effective date columns

Revision ID: b934f821a42e
Revises: 5f2787e56cd3
Create Date: 2016-08-10 17:34:17.396917

"""

# revision identifiers, used by Alembic.
revision = 'b934f821a42e'
down_revision = '5f2787e56cd3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('ongoing_enrollment_type', sa.String(length=16), nullable=True))
    op.add_column('cases', sa.Column('open_enrollment_type', sa.String(length=16), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'open_enrollment_type')
    op.drop_column('cases', 'ongoing_enrollment_type')
    ### end Alembic commands ###
