"""added_is_deleted_column

Revision ID: c3b655d2a87d
Revises: b99a192aa902
Create Date: 2016-06-21 15:45:22.729901

"""

# revision identifiers, used by Alembic.
revision = 'c3b655d2a87d'
down_revision = 'b99a192aa902'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('is_deleted', sa.Boolean(), server_default='FALSE', nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'is_deleted')
    ### end Alembic commands ###
