"""added timestamps for tracking signing status on enrollments

Revision ID: d1df6d638fa
Revises: 1f0764d8a293
Create Date: 2016-02-13 18:55:12.885575

"""

# revision identifiers, used by Alembic.
revision = 'd1df6d638fa'
down_revision = '1f0764d8a293'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment_applications', sa.Column('agent_signing_datetime', sa.DateTime(), nullable=True))
    op.add_column('enrollment_applications', sa.Column('applicant_signing_datetime', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollment_applications', 'applicant_signing_datetime')
    op.drop_column('enrollment_applications', 'agent_signing_datetime')
    ### end Alembic commands ###
