"""Added user href and filename to batch history

Revision ID: da452280ac3b
Revises: ced85f2cea4e
Create Date: 2016-09-15 12:13:46.667569

"""

# revision identifiers, used by Alembic.
revision = 'da452280ac3b'
down_revision = 'ced85f2cea4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment_import_batches', sa.Column('filename', sa.Unicode(), nullable=True))
    op.add_column('enrollment_import_batches', sa.Column('user_href', sa.Unicode(), nullable=True))
    op.create_index(op.f('ix_enrollment_import_batches_user_href'), 'enrollment_import_batches', ['user_href'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollment_import_batches_user_href'), table_name='enrollment_import_batches')
    op.drop_column('enrollment_import_batches', 'user_href')
    op.drop_column('enrollment_import_batches', 'filename')
    ### end Alembic commands ###
