"""Adding agency column and signing name to agents table

Revision ID: f60f14225715
Revises: 85c1dfc608a1
Create Date: 2016-03-15 21:08:10.268931

"""

# revision identifiers, used by Alembic.
revision = 'f60f14225715'
down_revision = '85c1dfc608a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('agency', sa.String(length=256), nullable=True))
    op.add_column('agents', sa.Column('signing_name', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'signing_name')
    op.drop_column('agents', 'agency')
    ### end Alembic commands ###
